### ISSUE TITLE
Need some clarity on Manual installation

### ISSUE THREAD

**Issue by gvikram18** [ceph/ceph-iscsi#100]
Hi,

Under the installation section, It's mentioned that for the daemons, we gotta copy the files to the respective paths.

    <archive_root>/usr/lib/systemd/system/rbd-target-gw.service --> /lib/systemd/system
    <archive_root>/usr/lib/systemd/system/rbd-target-api.service --> /lib/systemd/system
    <archive_root>/usr/bin/rbd-target-gw --> /usr/bin
    <archive_root>/usr/bin/rbd-target-api --> /usr/bin
    <archive_root>/usr/bin/gwcli --> /usr/bin

But, looking at the repo, there's no `usr/bin` folder. Only `usr/lib/systemd/system/` exists.
The files mentioned to be placed at `/usr/bin` are rbd-target-gw, rbd-target-api, gwcli. Now, are these same files as the ones present in repo as rbd-target-gw.py, rbd-target-api.py and gwcli.py respectively? Need some clarity on this.

**Comment by mikechristie** [comment]
Sorry about this. I missed this issue.

The docs are wrong. Just doing "python setup.py install" will install gwcli and the rbd-target-api and rbd-target-gw daemons to the correct places.

You do have to install the systemd unilt files still.

PR to fix the doc:

https://github.com/ceph/ceph-iscsi/pull/116
