### ISSUE TITLE
help error

### ISSUE THREAD

**Issue by jzxrm2006** [ceph/ceph-iscsi#103]
![image](https://user-images.githubusercontent.com/26538949/59167305-2a58da00-8b63-11e9-9c8b-d9227b6c307c.png)

**Comment by jzxrm2006** [comment]
ceph-iscsi-3.0

**Comment by mikechristie** [comment]
Did you do a rpm based install of the ceph packages like rados or did you compile it yourself?

If you used rpm, what version of ceph are you using and what is the version of the python rados rpm installed in your system? Do they match? Did a old distro rados rpm get installed?

**Comment by jzxrm2006** [comment]
Upgrade rados version
ok!
