### ISSUE TITLE
Unhandled exception: __init__() got an unexpected keyword argument 'control'

### ISSUE THREAD

**Issue by jzxrm2006** [ceph/ceph-iscsi#106]
![image](https://user-images.githubusercontent.com/26538949/59191055-fd331880-8bb0-11e9-9aa5-de2c7e2c7689.png)

![image](https://user-images.githubusercontent.com/26538949/59191049-f99f9180-8bb0-11e9-9f0b-b61400abc061.png)
![image](https://user-images.githubusercontent.com/26538949/59191065-04f2bd00-8bb1-11e9-86d3-43eb3fd17fab.png)
![image](https://user-images.githubusercontent.com/26538949/59191113-2653a900-8bb1-11e9-8285-34e9926fb876.png)
help~~

**Comment by dillaman** [comment]
Your python rtslib is out-of-date (too old)

**Comment by jzxrm2006** [comment]
@dillaman Thank you very much
