### ISSUE TITLE
 Failed : Gateway deletion failed, gateway(s) unavailable:pg-iscsi54239(UNKNOWN state),pg-iscsi54240(UNKNOWN state)

### ISSUE THREAD

**Issue by jzxrm2006** [ceph/ceph-iscsi#111]
![image](https://user-images.githubusercontent.com/26538949/59270428-0214cc80-8c84-11e9-87c6-976e672ee7c6.png)
Has stopped using
How to delete gateways?

**Comment by mikechristie** [comment]
You need to have rbd-target-api running on the gateways you have setup and are deleting so they can clean up the kernel.
