### ISSUE TITLE
opensuse and centos iscsi targets

### ISSUE THREAD

**Issue by Jazz9** [ceph/ceph-iscsi#119]
Hello,

I have a need to add a few opensuse iscsi targets as I need persistent reservations. This worked well but when I open the gwcli on the opensuse nodes I get:

SVR-ISCSI1:~ # gwcli
/iscsi-target...w2:iscsi-igw2> ls
AttributeError: 'Gateway' object has no attribute 'portal_ip_address'

I have checked the versions of gwcli and targetcli between the two and they are the same 
gwcli - 2.7
/usr/bin/targetcli version 2.1.fb49

The gwcli is working on the centos servers.

any ideas?

Glen

**Comment by ricardoasmarques** [comment]
Looks like you have updated the `ceph-iscsi` package in some nodes, but not all nodes. 

Check if you are running the same `ceph-iscsi` version in all nodes.

Also, what is the output of executing `# gwcli / export | grep version`?

**Comment by Jazz9** [comment]
Thanks for the reply.

All servers have version 10

SVR-ISCSI1:/ # gwcli / export | grep version
    "version": 10
SVR-ISCSI1:/ #

The opensuse servers have
SVR-ISCSI1:/ # rpm -q ceph-iscsi
ceph-iscsi-3.0+1556546618.g28a0e8a-lp151.1.1.noarch

The centos servers aren't installed with ceph-iscsi package ( manual git method )

What is the easiest way to get them the same?

**Comment by ricardoasmarques** [comment]
@Jazz9 all you have to do is update the `ceph-iscsi` package on your openSUSE server to the latest version:

```
# zypper ref
# zypper up ceph-iscsi
```
Then you should be able to use `gwcli` on your openSUSE servers.

**Comment by Jazz9** [comment]
Seems I may need to add a repo?

SVR-ISCSI1:/ # zypper up ceph-iscsi
Loading repository data...
Reading installed packages...
No update candidate for 'ceph-iscsi-3.0+1556546618.g28a0e8a-lp151.1.1.noarch'. The highest available version is already installed.
Resolving package dependencies...

Nothing to do.

**Comment by ricardoasmarques** [comment]
Try the following:

```
# zypper ar https://download.opensuse.org/repositories/filesystems:/ceph:/nautilus/openSUSE_Leap_15.1/filesystems:ceph:nautilus.repo
# zypper ref
# zypper up ceph-iscsi
```

**Comment by Jazz9** [comment]
That worked! Thankyou for your help.

2019-07-09T01:07:25.373707+10:00 localhost [RPM][1947]: erase ceph-iscsi-3.0+1556546618.g28a0e8a-lp151.1.1.noarch: success
2019-07-09T01:07:25.375168+10:00 localhost [RPM][1947]: install ceph-iscsi-3.0+1561993428.g70ec7a9-lp151.108.1.noarch: success

gwcli now works on the opensuse servers.
