### ISSUE TITLE
is it possible to map a LUN to multiple targets?

### ISSUE THREAD

**Issue by wuxingyi** [ceph/ceph-iscsi#124]
I read code and find mapping a LUN to multiple targets is prohibited in the following code snippet:

https://github.com/ceph/ceph-iscsi/blob/ec80bb1cc8b288b40bc35e03e4ba4c60daced938/rbd-target-api.py#L768

I tried to comment the above lines out and successfully mapped single LUN to two targets ONLY when I set `minimum_gateways` to 1 and run the gateway locally, when I run two gateways, it failed with error message: `Failed to add the LUN - Existing ALUA group tag for group ao in invalid state.`

**Comment by mikechristie** [comment]
It's just not supported right now. I do not have plans to add it. I am ok with patches if you have a use case and time to implement it. Closing the issue. Just make a PR with the patches.

**Comment by mikechristie** [comment]
Adding @ricardoasmarques because he was looking into this a long time ago. Not sure if he still is though.

**Comment by ricardoasmarques** [comment]
No plans to work on this from my end.
