### ISSUE TITLE
rbd-target-api hangs if DNS resolution times out

### ISSUE THREAD

**Issue by emmericp** [ceph/ceph-iscsi#136]
rbd-target-api becomes unresponsive if a DNS server is configured that doesn't reply.

Example: set `nameserver 8.8.8.8` in `/etc/resolv.conf` while having a default route installed that doesn't forward packets to the internet. Removing either the nameserver config or the whole default route fixes rbd-target-api instantly. That means only DNS timeouts are a problem as "no route to host" errors for DNS resolution are handled properly.

**Comment by emmericp** [comment]
All gateway names etc. configured here can be resolved via /etc/hosts on all gateways. This means this setup works fine on a setup without DNS until a bad DNS server is configured.

**Comment by JKJameson** [comment]
It is good practice to add your ceph hosts to /etc/hosts for this exact reason.
It used to be a requirement to the preflight checklist for ceph installations, but for some reason is no longer mentioned.

**Comment by emmericp** [comment]
See me second comment, all names can be resolved via /etc/hosts and it works fine with no DNS configured at all. It hangs as soon as a bad DNS is configured even though name resolution still works because /etc/hosts should take precedence.

**Comment by JKJameson** [comment]
The issue lies inutils.py
The Python function socket.getaddrinfo does not use /etc/hosts
Could you edit the source to use socket.gethostbyname instead, and see if this fixes the issue?

**Comment by mikechristie** [comment]
@JKJameson 

Is socket.getaddrinfo and missing /etc/hosts support a bug or documented somewhere? Is it possible to work around with /etc/nsswitch or is it something that is configurable?

**Comment by emmericp** [comment]
We have /etc/nsswitch configured to use /etc/hosts.

It's a setup that does not rely on DNS resolution at all. ceph-iscsi tries to do something with the DNS server anyways and hangs if it doesn't respond.

**Comment by emmericp** [comment]
Okay, the problem is IPv6 which we don't use here.

`resolve_ip_addresses` is called for all gateway hostnames on all API calls here https://github.com/ceph/ceph-iscsi/blob/06c7f2652a97c36ef965acc07bead92234e586c8/rbd-target-api.py#L83 to validate the caller IP. It's called for both IPv4 and IPv6, working fine for IPv4 but running into a long timeout for every single gateway on every request.
As a result `gwcli` doesn't work at all.


I don't think it's a good idea to call `getaddrinfo()` 2*n times for every single API call, proper solution would be to cache the whitelist of IPs that are allowed to call the API? We'll probably either just disable IPv6 here for now.

(Well, and obviously tell people to not misconfigure their DNS/network, but we see this misconfiguration a lot, it usually just doesn't matter)

**Comment by emmericp** [comment]
https://github.com/ceph/ceph-iscsi/commit/52820465347deaed922752fc1314e74588705974 already fixed this in master, I was only testing the released version, so I guess we can close this.
