### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Widmo** [ceph/ceph-iscsi#184]
Hi, 
fresh install, Centos 8, ceph Octopus. 

After reboot service **rbd-target-api** won't start. 
(Sometimes, after several tries it starts) 

Error log: 
`
Apr 20 19:05:35 ceph01 rbd-target-api[14745]: Traceback (most recent call last):
Apr 20 19:05:35 ceph01 rbd-target-api[14745]:  File "/usr/bin/rbd-target-api", line 2951, in <module>
Apr 20 19:05:35 ceph01 rbd-target-api[14745]:    main()
Apr 20 19:05:35 ceph01 rbd-target-api[14745]:  File "/usr/bin/rbd-target-api", line 2861, in main
Apr 20 19:05:35 ceph01 rbd-target-api[14745]:    osd_state_ok = ceph_gw.osd_blacklist_cleanup()
Apr 20 19:05:35 ceph01 rbd-target-api[14745]:  File "/usr/lib/python3.6/site-packages/ceph_iscsi_config/gateway.py", line 110, in osd_blacklist_cleanup
Apr 20 19:05:35 ceph01 rbd-target-api[14745]:    rm_ok = self.ceph_rm_blacklist(blacklist_entry.split(' ')[0])
Apr 20 19:05:35 ceph01 rbd-target-api[14745]:  File "/usr/lib/python3.6/site-packages/ceph_iscsi_config/gateway.py", line 46, in ceph_rm_blacklist
Apr 20 19:05:35 ceph01 rbd-target-api[14745]:    if ("un-blacklisting" in result) or ("isn't blacklisted" in result):
Apr 20 19:05:35 ceph01 rbd-target-api[14745]: TypeError: a bytes-like object is required, not 'str'
`

At another node, the same cluster, is running well. 
file `/etc/ceph/iscsi-gateway.cfg` is the same on both nodes. 

RPM: 
`Installed Packages
Name         : ceph-iscsi
Version      : 3.4
Release      : 1.el8`

**Comment by dillaman** [comment]
Fixed by #170
