### ISSUE TITLE
1 gateway is inaccessible - updates will be disabled

### ISSUE THREAD

**Issue by NUABO** [ceph/ceph-iscsi#188]
I got this kind of error when using ceph-iscsi, will it affect the use, how to eliminate it?

![image](https://user-images.githubusercontent.com/29769310/81383892-69acf380-9143-11ea-89e0-fcd7ab2101a0.png)

**Comment by mikechristie** [comment]
You will not be able to modify the setup. You need to figure out why gwcli cannot access rbd-target-api on that node. Check /var/log/rbd-target-api/* for errors.

You probably didn't set a login/password or ip address in /etc/ceph/iscsi-gateway.cfg.
