### ISSUE TITLE
Login failed with iSCSI PDU timed out

### ISSUE THREAD

**Issue by zhangdaolong** [ceph/ceph-iscsi#197]
I hope someone can help, or give a hint for a solution or the problem.
Thanks in advanced!

system and package info
-------------------------------------------------------
	kernel: 3.10.0-1127.el7.x86_64
	ceph:ceph-common-13.2.8-14

	tcmu-runner-1.5.2-1.el7.x86_64
	ceph-iscsi-3.4-1.el7.noarch

Target config
---------------------------------------------------------

        # targetcli 
	targetcli shell version 2.1.fb49
	Copyright 2011-2013 by Datera, Inc and others.
	For help on commands, type 'help'.

	/iscsi> ls
	o- iscsi .............................................................................................................. [Targets: 1]
	  o- iqn.1999-06.com.xxx.iscsi:chap ................................................................................ [TPGs: 2]
	    o- tpg1 ............................................................................................ [no-gen-acls, auth per-acl]
	    | o- acls ............................................................................................................ [ACLs: 1]
	    | | o- iqn.2019-10.com.xxx:pdu .............................................................. [1-way auth, Mapped LUNs: 0]
	    | o- luns ............................................................................................................ [LUNs: 0]
	    | o- portals ...................................................................................................... [Portals: 1]
	    |   o- 192.168.6.21:3260 ................................................................................................... [OK]
	    o- tpg2 ............................................................................................................. [disabled]
	      o- acls ............................................................................................................ [ACLs: 0]
	      o- luns ............................................................................................................ [LUNs: 0]
	      o- portals ...................................................................................................... [Portals: 1]
		o- 192.168.6.19:3260 ................................................................................................... [OK]
	/iscsi> 

Initator node
------------------------------------------------------------
	# iscsiadm -m discovery -t sendtargets -p 192.168.6.21:3260
	192.168.6.21:3260,1 iqn.1999-06.com.xxx.iscsi:chap
	192.168.6.19:3260,2 iqn.1999-06.com.xxx.iscsi:chap
	# iscsiadm -m node -T iqn.1999-06.com.xxx.iscsi:chap -o update --name node.session.auth.authmethod --value=CHAP
	# iscsiadm -m node -T iqn.1999-06.com.xxx.iscsi:chap --op update --name node.session.auth.username --value=username
	# iscsiadm -m node -T iqn.1999-06.com.xxx.iscsi:chap --op update --name node.session.auth.password --value=passwordpassword
	# iscsiadm -m node -T iqn.1999-06.com.xxx.iscsi:chap  -l
	Logging in to [iface: default, target: iqn.1999-06.com.xxx.iscsi:chap, portal: 10.127.6.20,3260] (multiple)
	Logging in to [iface: default, target: iqn.1999-06.com.xxx.iscsi:chap, portal: 192.168.6.21,3260] (multiple)
	Logging in to [iface: default, target: iqn.1999-06.com.xxx.iscsi:chap, portal: 192.168.6.21,3260] (multiple)
	Logging in to [iface: default, target: iqn.1999-06.com.xxx.iscsi:chap, portal: 192.168.6.19,3260] (multiple)
	iscsiadm: Could not login to [iface: default, target: iqn.1999-06.com.xxx.iscsi:chap, portal: 10.127.6.20,3260].
	iscsiadm: initiator reported error (8 - connection timed out)
	Login to [iface: default, target: iqn.1999-06.com.xxx.iscsi:chap, portal: 192.168.6.21,3260] successful.
	Login to [iface: default, target: iqn.1999-06.com.xxx.iscsi:chap, portal: 192.168.6.21,3260] successful.
	iscsiadm: Could not login to [iface: default, target: iqn.1999-06.com.xxx.iscsi:chap, portal: 192.168.6.19,3260].
	iscsiadm: initiator reported error (11 - iSCSI PDU timed out)
	iscsiadm: Could not log into all portals

Target node
--------------------------------------------------------
        # dmesg
	[Sat Jun 20 15:36:20 2020] Unexpected ret: -104 send data 112
	[Sat Jun 20 15:36:20 2020] tx_data returned -32, expecting 112.
	[Sat Jun 20 15:36:20 2020] iSCSI Login negotiation failed.
	[Sat Jun 20 15:36:37 2020] rx_data returned -104, expecting 60.
	[Sat Jun 20 15:36:37 2020] iSCSI Login negotiation failed.
	[Sat Jun 20 15:36:37 2020] Unexpected ret: -104 send data 112
	[Sat Jun 20 15:36:37 2020] tx_data returned -32, expecting 112.

.......

**Comment by shanehsu** [comment]
I am also seeing something similar. @zhangdaolong have you figured out what’s causing the problem? -104 seemed to indicate connection reset by peer in TCP. Some have suggested connection/host utilization/bond interface to be possible cause. Do you have any one of the above symptom in your cluster?

**Comment by zhangdaolong** [comment]
> I am also seeing something similar. @zhangdaolong have you figured out what’s causing the problem? -104 seemed to indicate connection reset by peer in TCP. Some have suggested connection/host utilization/bond interface to be possible cause. Do you have any one of the above symptom in your cluster?

Yes i solved this problem，The cause of the problem is that I set it "net.ipv4.tcp_low_latency=1"  in my system, I commented it in sysct.conf and this problem did not occur.
Hope the above information is useful to you

**Comment by shanehsu** [comment]
I solved it just this morning. It seemed that cephadm under 15.2.4 does not deploy tcmu-runner. Upgrading to a new version of Ceph automatically solves it. 

Would you mind closing your issue since you've solved it for housekeeping's sake? 😉

**Comment by zhangdaolong** [comment]
> I solved it just this morning. It seemed that cephadm under 15.2.4 does not deploy tcmu-runner. Upgrading to a new version of Ceph automatically solves it.
> 
> Would you mind closing your issue since you've solved it for housekeeping's sake? wink

ok
