### ISSUE TITLE
rpm: use systemd scriptlets macros

### ISSUE THREAD

**Issue by ktdreyer** [ceph/ceph-iscsi#40]
The RPM packaging for RHEL and Fedora currently hard-codes some systemd things. Like
```
BuildRequires:  systemd
```
or
```
/bin/systemctl --system daemon-reload &> /dev/null || :
/bin/systemctl --system enable rbd-target-gw &> /dev/null || :
/bin/systemctl --system enable rbd-target-api &> /dev/null || :
```

We can switch these out for scriptlets instead: https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_scriptlets

This will make it easier to get ceph-iscsi into Fedora if we follow the package guidelines here.

It will also make it easier to drop the dependency on systemd eventually when we run inside containers. [Fedora has a new %systemd_ordering macro for this](https://pagure.io/packaging-committee/issue/644), but I've not played around with it yet.

**Comment by mikechristie** [comment]
I'll handle it this week. I am in the process of removing the need for that rbd-target-gw interaction right now. When that is removed, I will also fix up the reload/enable stuff above and test it all together.

**Comment by ktdreyer** [comment]
No prob Mike, this is not urgent.
