### ISSUE TITLE
Use hosts, host-groups in iscsi target

### ISSUE THREAD

**Issue by hoanhdo** [ceph/ceph-iscsi#45]
Hi all.

i setup 2 ceph-iscsi gateway and 1 iscsi-initiator.

Ceph and ceph-iscsi version :

>ceph-iscsi-config-2.6-2.6.el7.noarch
python-ceph-argparse-14.1.0-0.el7.x86_64
libcephfs2-14.1.0-0.el7.x86_64
ceph-iscsi-cli-2.7-2.7.el7.noarch
python-cephfs-14.1.0-0.el7.x86_64
ceph-common-14.1.0-0.el7.x86_64
ceph-iscsi-tools-2.1-2.1.el7.noarch

tcmu, rtslib, targetcli version :
> python-rtslib-2.1.fb67-2.5.noarch
libtcmu-1.4.0-106.gd17d24e.el7.x86_64
targetcli-2.1.fb47-0.1.el7.noarch
tcmu-runner-1.4.0-106.gd17d24e.el7.x86_64

![image](https://user-images.githubusercontent.com/5550425/54252634-2a563780-457e-11e9-8994-3432137c7f09.png)

Ater create 2 hosts, i discovery iscsi target and login. Iscsi initiator map all lun.

![image](https://user-images.githubusercontent.com/5550425/54252670-4659d900-457e-11e9-8d1c-5eed3035a30c.png)

I want to 1 initiator use 1 hosts.
How i can restrict lun base hosts and host-groups.

Thanks.

**Comment by dillaman** [comment]
@hoanhdo You should use the multipath device for IO so that it properly fails over/back between the two iSCSI gateways. Since you have 2 LUNs exported over two gateways, you should expect 4 raw block devices.

**Comment by mikechristie** [comment]
@hoanhdo 

Use the multipath.conf for linux initiators here:

http://docs.ceph.com/docs/mimic/rbd/iscsi-initiator-linux

The multipath tools will do everything for you.
