### ISSUE TITLE
How can I delete the host of iscsi gateway under gwcli?

### ISSUE THREAD

**Issue by gzsy2000** [ceph/ceph-iscsi#55]
hi
   How can I delete the host of iscsi gateway under gwcli?

**Comment by dillaman** [comment]
I believe there is a delete command under the gateways node in the ```gwcli```

**Comment by gzsy2000** [comment]
I just did not find a command like "remove" under the gateway node.
My need is to delete a node under the iscsi gateway.If you know how to delete, please let me know, thank you.
E.g
/iscsi-target...ceph-target-3> pwd
/iscsi-target/iqn.2003-01.com.redhat.iscsi-gw:iscsi-igw/gateways/ceph-target-3
/iscsi-target...ceph-target-3> 
/             @gateways     @host-groups  @hosts        bookmarks     
cd            exit          get           goto          help          
info          ls            pwd           refresh       set

**Comment by gzsy2000** [comment]
I just did not find a command like "remove" under the gateway node.
My need is to delete a node under the iscsi gateway. If you know how to delete, please let me know, thank you.
E.g
/iscsi-target...ceph-target-3> pwd
/iscsi-target/iqn.2003-01.com.redhat.iscsi-gw:iscsi-igw/gateways/ceph-target-3
/iscsi-target...ceph-target-3> 
/             @gateways     @host-groups  @hosts        bookmarks     
cd            exit          get           goto          help          
info          ls            pwd           refresh       set

**Comment by mikechristie** [comment]
What version of ceph-iscsi are you using? You need 3.0. It's also in the gateways dir and not in the dir of the gateway.
