### ISSUE TITLE
Rbd-target-api.service failed to start

### ISSUE THREAD

**Issue by NUABO** [ceph/ceph-iscsi#85]
I have reported an error using gwcli:
[root@node1 tan]# gwcli 
Unable to access the configuration object : REST API failure, code : 404
GatewayError: 

>404 - Not Found: Use when object does not exists.  This will also be returned in the case where it might exist in SpringCM, but the user does not have access to it based on their security profile.  In this case the error message returned will be "Object does not exist or the user does not have access rights".

>[root@node1 tcmu-runner]# systemctl status  rbd-target-api.service
● rbd-target-api.service - Ceph iscsi target configuration API
   Loaded: loaded (/usr/lib/systemd/system/rbd-target-api.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Wed 2019-05-15 13:37:36 CST; 3min 45s ago
  Process: 81570 ExecStart=/usr/bin/rbd-target-api (code=exited, status=1/FAILURE)
 Main PID: 81570 (code=exited, status=1/FAILURE)
 May 15 13:37:36 node1 systemd[1]: Unit rbd-target-api.service entered failed state.
 May 15 13:37:36 node1 systemd[1]: rbd-target-api.service failed.
 May 15 13:37:36 node1 systemd[1]: rbd-target-api.service holdoff time over, scheduling restart.
 May 15 13:37:36 node1 systemd[1]: Stopped Ceph iscsi target configuration API.
 May 15 13:37:36 node1 systemd[1]: start request repeated too quickly for rbd-target-api.service
 May 15 13:37:36 node1 systemd[1]: Failed to start Ceph iscsi target configuration API.
 May 15 13:37:36 node1 systemd[1]: Unit rbd-target-api.service entered failed state.
 May 15 13:37:36 node1 systemd[1]: rbd-target-api.service failed.

The rpm version I am using is:
>ceph-iscsi-cli-2.6-1.el7.centos.noarch.rpm   
python-rtslib-2.1.67-1.noarch.rpm  
tcmu-runner-1.3.0-rc4.el7.centos.x86_64.rpm
ceph-iscsi-config-2.5-1.el7.centos.noarch.rpm  
targetcli-fb-2.1.fb48-1.noarch.rpm

thanks

**Comment by hoerup** [comment]
Please get some more log data from journalctl

**Comment by NUABO** [comment]
hi @hoerup, This is the log 

>[root@node1 ~]# journalctl  -e -u  rbd-target-api
May 17 15:10:58 node1 rbd-target-api[127359]: File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
May 17 15:10:58 node1 rbd-target-api[127359]: self.require(requires)[0].run_script(script_name, ns)
May 17 15:10:58 node1 rbd-target-api[127359]: File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1511, in run_script
May 17 15:10:58 node1 rbd-target-api[127359]: exec(script_code, namespace, namespace)
May 17 15:10:58 node1 rbd-target-api[127359]: File "/usr/lib/python2.7/site-packages/ceph_iscsi-3.0-py2.7.egg/EGG-INFO/scripts/rbd-target-api", line 2849, in <module>
May 17 15:10:58 node1 rbd-target-api[127359]: File "/usr/lib/python2.7/site-packages/ceph_iscsi-3.0-py2.7.egg/EGG-INFO/scripts/rbd-target-api", line 2792, in main
May 17 15:10:58 node1 rbd-target-api[127359]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 772, in run
May 17 15:10:58 node1 rbd-target-api[127359]: run_simple(host, port, self, **options)
May 17 15:10:58 node1 rbd-target-api[127359]: File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 710, in run_simple
May 17 15:10:58 node1 rbd-target-api[127359]: inner()
May 17 15:10:58 node1 rbd-target-api[127359]: File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 692, in inner
May 17 15:10:58 node1 rbd-target-api[127359]: passthrough_errors, ssl_context).serve_forever()
May 17 15:10:58 node1 rbd-target-api[127359]: File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 480, in make_server
May 17 15:10:58 node1 rbd-target-api[127359]: passthrough_errors, ssl_context)
May 17 15:10:58 node1 rbd-target-api[127359]: File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 410, in __init__
May 17 15:10:58 node1 rbd-target-api[127359]: HTTPServer.__init__(self, (host, int(port)), handler)
May 17 15:10:58 node1 rbd-target-api[127359]: File "/usr/lib64/python2.7/SocketServer.py", line 419, in __init__
May 17 15:10:58 node1 rbd-target-api[127359]: self.server_bind()
May 17 15:10:58 node1 rbd-target-api[127359]: File "/usr/lib64/python2.7/BaseHTTPServer.py", line 108, in server_bind
May 17 15:10:58 node1 rbd-target-api[127359]: SocketServer.TCPServer.server_bind(self)
May 17 15:10:58 node1 rbd-target-api[127359]: File "/usr/lib64/python2.7/SocketServer.py", line 430, in server_bind
May 17 15:10:58 node1 rbd-target-api[127359]: self.socket.bind(self.server_address)
May 17 15:10:58 node1 rbd-target-api[127359]: File "/usr/lib64/python2.7/socket.py", line 224, in meth
May 17 15:10:58 node1 rbd-target-api[127359]: return getattr(self._sock,name)(*args)
May 17 15:10:58 node1 rbd-target-api[127359]: socket.error: [Errno 98] Address already in use
May 17 15:10:58 node1 systemd[1]: rbd-target-api.service: main process exited, code=exited, status=1/FAILURE
May 17 15:10:58 node1 systemd[1]: Unit rbd-target-api.service entered failed state.
May 17 15:10:58 node1 systemd[1]: rbd-target-api.service failed.
May 17 15:10:58 node1 systemd[1]: rbd-target-api.service holdoff time over, scheduling restart.
May 17 15:10:58 node1 systemd[1]: Stopped Ceph iscsi target configuration API.
May 17 15:10:58 node1 systemd[1]: start request repeated too quickly for rbd-target-api.service
May 17 15:10:58 node1 systemd[1]: Failed to start Ceph iscsi target configuration API.
May 17 15:10:58 node1 systemd[1]: Unit rbd-target-api.service entered failed state.
May 17 15:10:58 node1 systemd[1]: rbd-target-api.service failed.

**Comment by mikechristie** [comment]
Can you try changing the api port in /etc/ceph/iscsi-gateway.cfg?

**Comment by NUABO** [comment]
@mikechristie  Thank you for your help, I solved this problem by modifying the port.
