### ISSUE TITLE
Failed to reconfigure : Unhandled exception: 'dict_keys' object is not subscriptable

### ISSUE THREAD

**Issue by Vascko** [ceph/ceph-iscsi#88]
Hey guys,

my environment is the same as in https://github.com/ceph/ceph-iscsi/issues/87 so this is a follow up (but separate issue).
I'm seeing the following error when trying to change a value in `gwcli` (or through CURL -X PUT) on a target:

```
/iscsi-target...-gw:iscsi-igw> reconfigure cmdsn_depth 512
Issuing reconfigure request: controls={"cmdsn_depth": "512"}
Failed to reconfigure : Unhandled exception: 'dict_keys' object is not subscriptable
/iscsi-target...-gw:iscsi-igw>
```

As mentioned in https://github.com/ceph/ceph-iscsi/issues/87, I'm using Fedora 30 which ships with Python 3.7.
The error seems to hint at the attempt to access an index of a dictionary's keys() method return value which, in Python 3, returns an iterable and no indexable object anymore as it did in Python 2.

https://github.com/ceph/ceph-iscsi/pull/2 seems to be adding Python3 support. What's the test coverage on Python 3?
I can see that there is a fix for an occurrence of what I mentioned above at https://github.com/ceph/ceph-iscsi/pull/2/files#diff-b97b10799eed7439f92d29f3e043232eL1309

I tried looking through the code if I can find more instances of what I described but I got lost pretty quick as I'm not really familiar with the code structure.

Thanks!

**Comment by ricardoasmarques** [comment]
@Vascko I've created PR https://github.com/ceph/ceph-iscsi/pull/91 that fixes an issue when running the `reconfigure` command on a python3 environment.

If this PR does not fix your issue, please paste the full `Traceback` from the `/var/log/rbd-target-api/rbd-target-api.log` file.
