### ISSUE TITLE
Missing .rpm file in the ceph-iscsi repo

### ISSUE THREAD

**Issue by gvikram18** [ceph/ceph-iscsi#90]
Hi,

It is listed under Readme that the installation can be done via rpm package provided. I am unable to find rpm package here

**Comment by hoerup** [comment]
See #64

**Comment by gvikram18** [comment]
> See #64

The ceph-iscsi rpms are 2.x
I am unable to find version 3.0

**Comment by mikechristie** [comment]
Closing this. Use the existing.
