### ISSUE TITLE
rbd-target-api service fails to start 

### ISSUE THREAD

**Issue by gsmith-cp** [ceph/ceph-iscsi#96]
ceph-iscsi version 3.0 - pulled from git repo May 23rd.

After initial config, this was working:

o- / ......................................................................................................................... [...]
 o- cluster ......................................................................................................... [Clusters: 1]
 | o- ceph .......................................................................................................... [HEALTH_WARN]
 |   o- pools .......................................................................................................... [Pools: 1]
 |   | o- rbd ................................................................... [(x3), Commit: 17.0T/18117898M (98%), Used: 192K]
 |   o- topology ............................................................................................... [OSDs: 12,MONs: 3]
 o- disks ....................................................................................................... [17.0T, Disks: 1]
 | o- rbd ........................................................................................................... [rbd (17.0T)]
 |   o- windata ............................................................................................. [rbd/windata (17.0T)]
 o- iscsi-targets ............................................................................... [DiscoveryAuth: None, Targets: 1]
   o- iqn.2018-10.com.cruisesystem.ho:ho-ceph1 ...................................................................... [Gateways: 1]
     o- disks .......................................................................................................... [Disks: 1]
     | o- rbd/windata ........................................................................................... [Owner: ho-ceph1]
     o- gateways ............................................................................................ [Up: 1/1, Portals: 1]
     | o- ho-ceph1 ............................................................................................. [172.16.0.10 (UP)]
     o- host-groups .................................................................................................. [Groups : 0]
     o- hosts .............................................................................................. [Hosts: 1: Auth: CHAP]
       o- iqn.1991-05.com.microsoft:storage01.ho.cruisesystem.com ................................... [Auth: CHAP, Disks: 1(17.0T)]
         o- lun 0 ........................................................................... [rbd/windata(17.0T), Owner: ho-ceph1]

after rebooting the server, I get these errors in /var/log/messages:

May 29 12:42:24 ho-ceph1 systemd: Started Ceph iscsi target configuration API.
May 29 12:42:24 ho-ceph1 journal: Processing osd blacklist entries for this node
May 29 12:42:24 ho-ceph1 journal: Started the configuration object watcher
May 29 12:42:24 ho-ceph1 journal: Checking for config object changes every 1s
May 29 12:42:25 ho-ceph1 journal: No OSD blacklist entries found
May 29 12:42:25 ho-ceph1 journal: Reading the configuration object to update local LIO configuration
May 29 12:42:25 ho-ceph1 journal: Processing Gateway configuration
May 29 12:42:25 ho-ceph1 journal: Setting up iqn.2018-10.com.cruisesystem.ho:ho-ceph1
May 29 12:42:25 ho-ceph1 journal: (Gateway.load_config) successfully loaded existing target definition
May 29 12:42:25 ho-ceph1 journal: Processing LUN configuration
May 29 12:42:25 ho-ceph1 journal: iqn.2018-10.com.cruisesystem.ho:ho-ceph1 - Processing client configuration
May 29 12:42:25 ho-ceph1 rbd-target-api: Traceback (most recent call last):
May 29 12:42:25 ho-ceph1 rbd-target-api: File "/usr/bin/rbd-target-api", line 5, in <module>
May 29 12:42:25 ho-ceph1 rbd-target-api: pkg_resources.run_script('ceph-iscsi==3.0', 'rbd-target-api')
May 29 12:42:25 ho-ceph1 rbd-target-api: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
May 29 12:42:25 ho-ceph1 rbd-target-api: self.require(requires)[0].run_script(script_name, ns)
May 29 12:42:25 ho-ceph1 rbd-target-api: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
May 29 12:42:25 ho-ceph1 rbd-target-api: exec_(script_code, namespace, namespace)
May 29 12:42:25 ho-ceph1 rbd-target-api: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
May 29 12:42:25 ho-ceph1 rbd-target-api: exec("""exec code in globs, locs""")
May 29 12:42:25 ho-ceph1 rbd-target-api: File "<string>", line 1, in <module>
May 29 12:42:25 ho-ceph1 rbd-target-api: File "/usr/lib/python2.7/site-packages/ceph_iscsi-3.0-py2.7.egg/EGG-INFO/scripts/rbd-target-api", line 2849, in <module>
May 29 12:42:25 ho-ceph1 rbd-target-api: File "/usr/lib/python2.7/site-packages/ceph_iscsi-3.0-py2.7.egg/EGG-INFO/scripts/rbd-target-api", line 2764, in main
May 29 12:42:25 ho-ceph1 rbd-target-api: File "build/bdist.linux-x86_64/egg/ceph_iscsi_config/gateway.py", line 239, in define
May 29 12:42:25 ho-ceph1 rbd-target-api: File "build/bdist.linux-x86_64/egg/ceph_iscsi_config/gateway.py", line 212, in define_targets
May 29 12:42:25 ho-ceph1 rbd-target-api: File "build/bdist.linux-x86_64/egg/ceph_iscsi_config/gateway.py", line 186, in define_target
May 29 12:42:25 ho-ceph1 rbd-target-api: File "build/bdist.linux-x86_64/egg/ceph_iscsi_config/client.py", line 283, in define_clients
May 29 12:42:25 ho-ceph1 rbd-target-api: File "build/bdist.linux-x86_64/egg/ceph_iscsi_config/client.py", line 759, in __init__
May 29 12:42:25 ho-ceph1 rbd-target-api: TypeError: object of type 'NoneType' has no len()
May 29 12:42:25 ho-ceph1 systemd: rbd-target-api.service: main process exited, code=exited, status=1/FAILURE
May 29 12:42:25 ho-ceph1 systemd: Unit rbd-target-api.service entered failed state.
May 29 12:42:25 ho-ceph1 systemd: rbd-target-api.service failed.
May 29 12:42:26 ho-ceph1 systemd: rbd-target-api.service holdoff time over, scheduling restart.
May 29 12:42:26 ho-ceph1 systemd: Stopped Ceph iscsi target configuration API.

system is running centOS 7-1810 with kernel 3.10.0-957.12.2.el7.x86_64

the only changes to the default iscsi-gateway.cfg are the trusted IP list, securing the api with a self-signed cert and:
minimum_gateways = 1

The health warn in the status above was because I forgot to enable the rbd for the pool - and has been corrected since.

I had everything working with the settings outlined above for iscsi-gateway.cfg

also, If I remove both the rbd disk image and rbd pool and reconfig from scratch, I can get everything working again... it just never survives reboot

**Comment by mikechristie** [comment]
Just one quick warning first. minimum_gateways must be 2 or more. It is not the cause of your crash, but later on when you try to add disks and do other management operations you will get a error about that.

For the git code you are using, do you mean you are using the head of the master branch or using the head from the 3.0 tag?

**Comment by gsmith-cp** [comment]
I cloned the master branch of ceph-iscsi on my 23rd and complied the source according to the instructions in the ceph documentation

**Comment by mikechristie** [comment]
What is the output of

radios get -p rbd gateway.conf - | grep encryption_enabled

?

**Comment by mikechristie** [comment]
And for the host

iqn.1991-05.com.microsoft:storage01.ho.cruisesystem.com

did you get to the step where you enabled CHAP and set a username and password yet or had that step not yet been completed?

**Comment by gsmith-cp** [comment]
"mutual_password_encryption_enabled": false,
        "password_encryption_enabled": false,
                        "mutual_password_encryption_enabled": false,
                        "password_encryption_enabled": true,


Yes, I had CHAP authentication configured and working

**Comment by gsmith-cp** [comment]
Here's the API log from me setting up the ISCSI gateway yesterday
[API_log_from_setup.txt](https://github.com/ceph/ceph-iscsi/files/3234548/API_log_from_setup.txt)

**Comment by mikechristie** [comment]
Have you setup a /etc/ceph/iscsi-gateway.key and iscsi-gateway-pub.key file?

It looks like the password did not get encrypted correctly. Later when we try to access it during daemon initialization we hit your crash.

**Comment by gsmith-cp** [comment]
I do have an iscsi-gateway.key and iscsi-gateway-pub.key file in place - I generated a self-signed cert as follows:

openssl req -newkey rsa:2048 -nodes -keyout iscsi-gateway.key -x509 -days 365 -out iscsi-gateway-pub.key

...interesting on the password not getting encrypted correctly. 

I'll check through my notes  - i think there was an issue due to an unsatisfied dependency related to python crypto i encountered during my install.

**Comment by gsmith-cp** [comment]
OK when I tried initially tried to compile ceph-iscsi, it failed due to a missing python cryptography module - 

Here's what I initially installed in CentOS (as per ceph documentation):
 
yum install libnl3 kmod-libs python-kmod python-pyudev python-gobject python-urwid pyparsing python-netaddr python-netifaces python-crypto python-requests python-flask pyOpenSSL

here's what I installed in addition to the packages above that allowed me to compile ceph-iscsi successfully:

yum install python2-cryptography python2-crypto

**Comment by gsmith-cp** [comment]
Is it possible to simple disable the CHAP authentication or reset the chap username and password outside of using the gwcli?

**Comment by gsmith-cp** [comment]
UPDATE!!!!

I installed all the dependencies on a different node of my cluster; did a fresh pull from git for tcmu-runner, rtslib-fb, configshell-fb, targetcli-fb and ceph-iscsi; built everything and then configured the iscsi-target from that node and everything now works and survives rebooting!!!!

Thanks for your help @mikechristie !!! Your narrowing down the issue to the password encryption helped tremendously!!!
